<a href="https://colab.research.google.com/github/Ritikkumar9828155803/Ritik-Kumar_24-27-20/blob/main/Assn2_Ritik_Kumar_10_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# NAME-- RITIK KUMAR , REG NO. -- 24-27-20 , PROGRAMME-- MTECH DATA SCIENCE ,  ASSIGNEMENT NO.2


In [9]:
import numpy as np

# **Q1**

##**(a)**

In [10]:

var1 = np.arange(0, 30)
print("var1:\n", var1)
print("Shape of var1:", var1.shape)


var1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Shape of var1: (30,)


# **(b)**

In [11]:
var2 = var1.reshape(6, 5)
print("\nvar2:\n", var2)
print("Shape of var2:", var2.shape)



var2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Shape of var2: (6, 5)


# **(c)**

In [12]:
var3 = var1.reshape(2, 3, 5)
print("\nvar3:\n", var3)
print("Shape of var3:", var3.shape)



var3:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
Shape of var3: (2, 3, 5)


# **(d)**

In [13]:
var2[1, 0] = -1
print("\nModified var2:\n", var2)
print("var1 after modification:\n", var1)
print("var3 after modification:\n", var3)




Modified var2:
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
var1 after modification:
 [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
var3 after modification:
 [[[ 0  1  2  3  4]
  [-1  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# **(e)**

In [14]:
sum_second_dimension = np.sum(var3, axis=1)
print("\nSum over the second dimension of var3:\n", sum_second_dimension)


sum_third_dimension = np.sum(var3, axis=2)
print("\nSum over the third dimension of var3:\n", sum_third_dimension)


sum_first_third_dimensions = np.sum(var3, axis=(0, 2))
print("\nSum over both the first and third dimensions of var3:\n", sum_first_third_dimensions)



Sum over the second dimension of var3:
 [[ 9 18 21 24 27]
 [60 63 66 69 72]]

Sum over the third dimension of var3:
 [[ 10  29  60]
 [ 85 110 135]]

Sum over both the first and third dimensions of var3:
 [ 95 139 195]


# **(f)**

In [15]:
second_row = var2[1, :]
print("\nSecond row of var2:\n", second_row)

last_column = var2[:, -1]
print("\nLast column of var2:\n", last_column)

top_right_submatrix = var2[:2, -2:]
print("\nTop-right 2x2 submatrix of var2:\n", top_right_submatrix)



Second row of var2:
 [-1  6  7  8  9]

Last column of var2:
 [ 4  9 14 19 24 29]

Top-right 2x2 submatrix of var2:
 [[3 4]
 [8 9]]


# **Q2**

# **(a)**

In [16]:
vector = np.arange(10) + 1

print("Vector from 1 to 10:\n", vector)


Vector from 1 to 10:
 [ 1  2  3  4  5  6  7  8  9 10]


# **(b)**

In [17]:
A = vector.reshape(10, 1) + vector

print("\nMatrix A (i + j):\n", A)



Matrix A (i + j):
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


# **(c)**

In [18]:
import numpy.random as npr

data = np.exp(npr.randn(50, 5))

print("\nFake dataset (first 5 rows):\n", data[:5])



Fake dataset (first 5 rows):
 [[0.36972398 0.62461415 0.44132567 2.32253175 0.46557803]
 [4.24128737 0.55735688 0.30824983 1.12843483 0.57043811]
 [2.96030274 1.15247165 0.73240487 2.26155284 2.27866102]
 [3.62626136 4.0202148  0.35835231 1.67423033 0.5870188 ]
 [0.45195534 3.90099921 1.1700023  1.96388544 0.65100518]]


# **(d)**

In [19]:
data = np.exp(npr.randn(50, 5))

print("\nFake dataset (first 5 rows):\n", data[:5])




Fake dataset (first 5 rows):
 [[2.0737544  1.44204018 0.46205676 3.79678037 2.1495915 ]
 [1.68135525 0.4743572  2.78826481 0.98632706 7.42707544]
 [0.95889162 4.71558397 0.16756369 0.39149434 1.2276154 ]
 [2.37234026 1.04260198 0.36463034 0.26053463 0.34485207]
 [1.36901927 0.58972205 3.44294984 2.89354829 0.34695594]]


# **(e)**

In [20]:
mean_col = np.mean(data, axis=0)

std_col = np.std(data, axis=0)

print("\nMean of each column:\n", mean_col)
print("Standard deviation of each column:\n", std_col)



Mean of each column:
 [1.70387959 1.53275199 1.2901445  1.70066947 1.45015594]
Standard deviation of each column:
 [1.76645649 1.24952667 1.46875491 1.43335862 1.27627522]


# **(f)**

In [21]:
normalized = (data - mean_col) / std_col


mean_normalized = np.mean(normalized, axis=0)
std_normalized = np.std(normalized, axis=0)

print("\nMean of each column (after normalization):\n", mean_normalized)
print("Standard deviation of each column (after normalization):\n", std_normalized)



Mean of each column (after normalization):
 [-1.34336986e-16  2.22044605e-17 -1.31006317e-16 -8.88178420e-17
 -2.22044605e-16]
Standard deviation of each column (after normalization):
 [1. 1. 1. 1. 1.]


# **Q3**

# **(a)**

In [22]:
def vandermonde(N):

    vec = np.arange(1, N+1)
    vander_matrix = vec[:, None] ** np.arange(N)
    return vander_matrix

N = 12
vander = vandermonde(N)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

# **(b)**

In [23]:
x = np.ones(12)

b = np.dot(vander, x)

print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


# **(c)**

In [24]:
V_inv = np.linalg.inv(vander)

x_naive = np.dot(V_inv, b)

print("Result of x using matrix inversion:", x_naive)

Result of x using matrix inversion: [-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


# **(d)**

In [25]:
x_solve = np.linalg.solve(vander, b)

print("Result of x using np.linalg.solve:", x_solve)

Result of x using np.linalg.solve: [0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]
